In [1]:
#!/usr/bin/python3
import pywikibot

site = pywikibot.Site("en", "wikipedia")
page = pywikibot.Page(site, "Douglas Adams")
item = pywikibot.ItemPage.fromPage(page)

print(item)

[[wikidata:Q42]]

In [2]:
print(dir(item))

['DATA_ATTRIBUTES', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_cache_attrs', '_check_bot_may_edit', '_cmpkey', '_content', '_cosmetic_changes_hook', '_defined_by', '_getInternals', '_isredir', '_latest_cached_revision', '_link', '_namespace', '_normalizeData', '_pageid', '_revid', '_revisions', '_save', 'addClaim', 'aliases', 'applicable_protections', 'autoFormat', 'backlinks', 'botMayEdit', 'categories', 'change_category', 'claims', 'clear_cache', 'concept_uri', 'content_model', 'contributors', 'coordinates', 'create_short_link', 'data_item', 'data_repository', 'defaultsort', 'delete', 'depth', 'descriptions', 'editAliases', 'editDescriptions', 'editEntity', 'editLabels', 'editTime', 'embeddedin', 'entity_type', 'exists', 'expand_text', 'extlinks', 'extract', 'fromPage', 'from_entity_uri', 'full_url', 'get', 'getCategoryRedirectTarget', 'getDeletedRevision', 'getID', 'getOldVersion', 'getRedirectTarget', 'getReferences', 'getSitelink', 'getVersionHistoryTable', 'get_data_for_new_entity', 'get_parsed_page', 'has_content', 'has_deleted_revisions', 'has_permission', 'id', 'image_repository', 'imagelinks', 'interwiki', 'isAutoTitle', 'isCategoryRedirect', 'isDisambig', 'isIpEdit', 'isRedirectPage', 'isStaticRedirect', 'isTalkPage', 'is_categorypage', 'is_filepage', 'is_flow_page', 'is_valid_id', 'iterlanglinks', 'iterlinks', 'itertemplates', 'labels', 'langlinks', 'lastNonBotUser', 'latest_revision', 'latest_revision_id', 'linkedPages', 'loadDeletedRevisions', 'markDeletedRevision', 'mergeInto', 'merge_history', 'move', 'moved_target', 'namespace', 'oldest_revision', 'page_image', 'pageid', 'permalink', 'preloadText', 'properties', 'protect', 'protection', 'purge', 'put', 'redirects', 'removeClaims', 'removeSitelink', 'removeSitelinks', 'repo', 'revision_count', 'revisions', 'save', 'section', 'setSitelink', 'setSitelinks', 'set_redirect_target', 'site', 'sitelinks', 'templates', 'text', 'title', 'title_pattern', 'toJSON', 'toggleTalkPage', 'touch', 'undelete', 'userName', 'version', 'watch']

In [3]:
print(item.exists())

True

In [4]:
item_dict = item.get()
print(item_dict.keys())

dict_keys(['labels', 'descriptions', 'aliases', 'claims', 'sitelinks'])

The next important method is item.get() which turns the whole item into a dictionary. Add the following lines to the example and run it again.

So now we know that the returned dictionary had the previous keys, and if we are interested in the labels we can add print(item_dict["labels"]) in the example. This will output

In [6]:
print(item_dict["labels"])

<class 'pywikibot.page._collections.LanguageDict'>({'en': 'Douglas Adams', 'fr': 'Douglas Adams', 'ru': 'Дуглас Адамс', 'pl': 'Douglas Adams', 'it': 'Douglas Adams', 'en-gb': 'Douglas Adams', 'nb': 'Douglas Adams', 'es': 'Douglas Adams', 'en-ca': 'Douglas Adams', 'hr': 'Douglas Adams', 'pt': 'Douglas Adams', 'ko': '더글러스 애덤스', 'nl': 'Douglas Adams', 'el': 'Ντάγκλας Άνταμς', 'ar': 'دوغلاس آدمز', 'arz': 'دوجلاس ادامز', 'bar': 'Douglas Adams', 'be': 'Дуглас Адамс', 'bg': 'Дъглас Адамс', 'bs': 'Douglas Adams', 'ca': 'Douglas Adams', 'cs': 'Douglas Adams', 'cy': 'Douglas Adams', 'da': 'Douglas Adams', 'eo': 'Douglas Adams', 'et': 'Douglas Adams', 'fa': 'داگلاس آدامز', 'fi': 'Douglas Adams', 'ga': 'Douglas Adams', 'gl': 'Douglas Adams', 'he': 'דאגלס אדמס', 'hu': 'Douglas Adams', 'id': 'Douglas Adams', 'io': 'Douglas Adams', 'is': 'Douglas Adams', 'ja': 'ダグラス・アダムズ', 'jv': 'Douglas Adams', 'ka': 'დაგლას ადამსი', 'la': 'Duglassius Adams', 'lv': 'Duglass Adamss', 'mk': 'Даглас Адамс', 'mr': 'डग्लस अॅडम्स', 'nn': 'Douglas Adams', 'ro': 'Douglas Adams', 'sco': 'Douglas Adams', 'sh': 'Douglas Adams', 'sk': 'Douglas Adams', 'sl': 'Douglas Adams', 'sq': 'Douglas Adams', 'sr': 'Даглас Адамс', 'sv': 'Douglas Adams', 'ta': 'டக்ளஸ் ஆடம்ஸ்', 'tr': 'Douglas Adams', 'uk': 'Дуглас Адамс', 'vi': 'Douglas Adams', 'zh': '道格拉斯·亞當斯', 'zh-cn': '道格拉斯·亚当斯', 'zh-hans': '道格拉斯·亚当斯', 'zh-hant': '道格拉斯·亞當斯', 'de-ch': 'Douglas Adams', 'pt-br': 'Douglas Adams', 'zh-sg': '道格拉斯·亚当斯', 'zh-my': '道格拉斯·亚当斯', 'zh-hk': '道格拉斯·亞當斯', 'zh-tw': '道格拉斯·亞當斯', 'zh-mo': '道格拉斯·亞當斯', 'war': 'Douglas Adams', 'be-tarask': 'Дуглас Адамз', 'vep': 'Adams Duglas', 'ur': 'ڈگلس ایڈم', 'oc': 'Douglas Adams', 'af': 'Douglas Adams', 'an': 'Douglas Adams', 'br': 'Douglas Adams', 'eu': 'Douglas Adams', 'lb': 'Douglas Adams', 'lmo': 'Douglas Adams', 'lt': 'Douglas Adams', 'nds': 'Douglas Adams', 'nds-nl': 'Douglas Adams', 'pms': 'Douglas Adams', 'vec': 'Douglas Adams', 'wa': 'Douglas Adams', 'sr-ec': 'Даглас Адамс', 'sr-el': 'Daglas Adams', 'de': 'Douglas Adams', 'ckb': 'دەگلاس ئادمز', 'fo': 'Douglas Adams', 'kl': 'Douglas Adams', 'gsw': 'Douglas Adams', 'te': 'డగ్లస్ ఆడమ్స్', 'si': 'ඩග්ලස් ඇඩම්ස්', 'bn': 'ডগলাস অ্যাডামস', 'hi': 'डग्लस अ\u200dडम्स', 'rwr': 'डग्लस अ\u200dडम्स', 'mg': 'Douglas Adams', 'ml': 'ഡഗ്ലസ് ആഡംസ്', 'gu': 'ડગ્લાસ એડમ્સ', 'hy': 'Դուգլաս Ադամս', 'ast': 'Douglas Adams', 'co': 'Douglas Adams', 'de-at': 'Douglas Adams', 'frp': 'Douglas Adams', 'fur': 'Douglas Adams', 'gd': 'Douglas Adams', 'ia': 'Douglas Adams', 'ie': 'Douglas Adams', 'kg': 'Douglas Adams', 'li': 'Douglas Adams', 'lij': 'Douglas Adams', 'min': 'Douglas Adams', 'ms': 'Douglas Adams', 'nap': 'Douglas Adams', 'nrm': 'Douglas Adams', 'pcd': 'Douglas Adams', 'rm': 'Douglas Adams', 'sc': 'Douglas Adams', 'scn': 'Douglas Adams', 'sw': 'Douglas Adams', 'vls': 'Douglas Adams', 'vo': 'Douglas Adams', 'wo': 'Douglas Adams', 'zu': 'Douglas Adams', 'az': 'Duqlas Noel Adams', 'ak': 'Doglas Adams', 'or': 'ଡଗ୍\u200cଲାସ୍\u200c ଆଦାମ୍\u200cସ', 'kn': 'ಡಗ್ಲಸ್ ಆಡಮ್ಸ್', 'ne': 'डगलस एडम्स', 'mrj': 'Адамс', 'th': 'ดักลัส แอดัมส์', 'pa': 'ਡਗਲਸ ਐਡਮਜ਼', 'tcy': 'ಡಾಗ್ಲಸ್ ಆಡಮ್ಸ್', 'tl': 'Douglas Adams', 'ext': 'Douglas Adams', 'azb': 'داقلاس آدامز', 'lfn': 'Douglas Adams', 'nan': 'Douglas Adams', 'ky': 'Дуглас Адамс', 'bho': 'डगलस एडम्स', 'wuu': '道格拉斯·亚当斯', 'yue': '道格拉斯亞當斯', 'pnb': 'ڈگلس ایڈمس', 'sje': 'Douglas Adams', 'se': 'Douglas Adams', 'smn': 'Douglas Adams', 'sms': 'Douglas Adams', 'sma': 'Douglas Adams', 'smj': 'Douglas Adams', 'bm': 'Douglas Adams', 'frc': 'Douglas Adams', 'jam': 'Douglas Adams', 'kab': 'Douglas Adams', 'pap': 'Douglas Adams', 'prg': 'Douglas Adams', 'rgn': 'Douglas Adams', 'vmf': 'Douglas Adams', 'nqo': 'ߘߎߜ߭ߑߟߊߛ ߊߘߊߡߛ', 'fy': 'Douglas Adams', 'hsb': 'Douglas Adams', 'yi': 'דאַגלאַס אַדאַמס', 'kw': 'Douglas Adams', 'ms-arab': 'دݢلس ايدمﺯ', 'jut': 'Douglas Adams'})

By the curly braces you can tell that you are getting a dictionary, whose keys are the Wikipedia language codes, and whose values are the current label in that language. In addition you can see the big advantage of Python 3: we get all the UTF-8 characters for free and the output is much more readable than for Farsi for example: {..., u'fa': u'\u062f\u0627\u06af\u0644\u0627\u0633 \u0622\u062f\u0627\u0645\u0632', ...}.

In [10]:
import os 
import pandas as pd
import numpy as np

In [35]:
os.chdir('C:/Users/nerea/OneDrive/Documentos/EPFL_MASTER/MA3/ADA/MovieSummaries')
df = pd.read_csv("character.metadata.tsv", sep='\t', header=None)
df.columns = ('Wikipedia movie ID', 'Freebase movie ID', 'Movie release date',
              'Character name', 'Actor date of birth', 'Actor gender',
              'Actor height (in meters)', 'Actor ethnicity (Freebase ID)', 'Actor name', 
              'Actor age at movie release', 'Freebase character/actor map ID', 'Freebase character ID', 
              'Freebase actor ID')
df.head()

,Wikipedia movie ID,Freebase movie ID,Movie release date,Character name,Actor date of birth,Actor gender,Actor height (in meters),Actor ethnicity (Freebase ID),Actor name,Actor age at movie release,Freebase character/actor map ID,Freebase character ID,Freebase actor ID
0,975900,/m/03vyhn,2001-08-24,Akooshay,1958-08-26,F,1.620,NaN,Wanda De Jesus,42.0,/m/0bgchxw,/m/0bgcj3x,/m/03wcfv7
1,975900,/m/03vyhn,2001-08-24,Lieutenant Melanie Ballard,1974-08-15,F,1.780,/m/044038p,Natasha Henstridge,27.0,/m/0jys3m,/m/0bgchn4,/m/0346l4
2,975900,/m/03vyhn,2001-08-24,Desolation Williams,1969-06-15,M,1.727,/m/0x67,Ice Cube,32.0,/m/0jys3g,/m/0bgchn_,/m/01vw26l
3,975900,/m/03vyhn,2001-08-24,Sgt Jericho Butler,1967-09-12,M,1.750,NaN,Jason Statham,33.0,/m/02vchl6,/m/0bgchnq,/m/034hyc
4,975900,/m/03vyhn,2001-08-24,Bashira Kincaid,1977-09-25,F,1.650,NaN,Clea DuVall,23.0,/m/02vbb3r,/m/0bgchp9,/m/01y9xg

In [33]:
df_2 = pd.read_csv("movie.metadata.tsv", sep='\t', header=None)

In [64]:
df_2.columns = ('Wikipedia movie ID' , 'Freebase movie ID' , 'Movie name' , 
                'Movie release date' , 'Movie box office revenue' , 
                'Movie runtime' , 'Movie languages' , 'Movie countries' , 'Movie genres')

In [102]:
df_2['Movie box office revenue'].size

81741

In [101]:
df_2['Movie box office revenue'].dropna()

0         14010832.0
7          3600000.0
13        10161099.0
17       102272727.0
21           21521.0
            ...
81695    288752301.0
81720     15369573.0
81725      6944471.0
81726     22886222.0
81732      1847671.0
Name: Movie box office revenue, Length: 8401, dtype: float64

In [107]:
df_2.head(30)

,Wikipedia movie ID,Freebase movie ID,Movie name,Movie release date,Movie box office revenue,Movie runtime,Movie languages,Movie countries,Movie genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"
5,13696889,/m/03cfc81,The Gangsters,1913-05-29,NaN,35.0,"{""/m/06ppq"": ""Silent film"", ""/m/02h40lc"": ""Eng...","{""/m/09c7w0"": ""United States of America""}","{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen..."
6,18998739,/m/04jcqvw,The Sorcerer's Apprentice,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0hzlz"": ""South Africa""}","{""/m/0hqxf"": ""Family Film"", ""/m/01hmnh"": ""Fant..."
7,10408933,/m/02qc0j7,Alexander's Ragtime Band,1938-08-16,3600000.0,106.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/04t36"": ""Musical"", ""/m/01z4y"": ""Comedy"", ..."
8,9997961,/m/06_y2j7,Contigo y aquí,1974,NaN,NaN,"{""/m/06nm1"": ""Spanish Language""}","{""/m/0jgd"": ""Argentina""}","{""/m/04t36"": ""Musical"", ""/m/07s9rl0"": ""Drama"",..."
9,2345652,/m/075f66,City of the Dead,1960,NaN,76.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/03npn"": ""Horror"", ""/m/0fdjb"": ""Supernatur..."
10,175026,/m/017n1p,Sarah and Son,1930,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/07s9rl0"": ""Drama"", ""/m/01g6gs"": ""Black-an..."
11,24229100,/m/07kjkz6,Lady Snowblood 2: Love Song of Vengeance,1974,NaN,89.0,"{""/m/03_9r"": ""Japanese Language""}","{""/m/03_3d"": ""Japan""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/01jfsb"": ""Th..."
12,6631279,/m/0gffwj,Little city,1997-04-04,NaN,93.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/06cvj"": ""Romantic comedy"", ""/m/0hj3n0w"": ..."
13,171005,/m/016ywb,Henry V,1989-11-08,10161099.0,137.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/04xvh5"": ""Costume drama"", ""/m/082gq"": ""Wa..."
14,18296435,/m/04cqrs4,Aaah Belinda,1986,NaN,NaN,"{""/m/02hwyss"": ""Turkish Language""}","{""/m/01znc_"": ""Turkey""}","{""/m/01z4y"": ""Comedy""}"
15,11250635,/m/02r52hc,The Mechanical Monsters,NaN,NaN,NaN,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/06n90"": ""Science Fiction"", ""/m/03k9fj"": ""..."
16,30388930,/m/0g5qvzg,1919,1984,NaN,99.0,{},{},"{""/m/07s9rl0"": ""Drama""}"
17,77856,/m/0kcn7,Mary Poppins,1964-08-27,102272727.0,139.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/0hj3myq"": ""Children's/Family"", ""/m/04t36""..."
18,32456683,/m/0gyryjt,Die Fahne von Kriwoj Rog,1967,NaN,108.0,"{""/m/04306rv"": ""German Language""}","{""/m/03f2w"": ""German Democratic Republic""}",{}
19,33420460,/m/0gj30jx,Keep the Change,1992,NaN,97.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/07s9rl0"": ""Drama""}"
20,175024,/m/017n1b,The Devil's Holiday,1930,NaN,NaN,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02l7c8"": ""Romance Film"", ""/m/07s9rl0"": ""D..."
21,612710,/m/02wjqm,New Rose Hotel,1999-10-01,21521.0,92.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
22,21926710,/m/05p45cv,White on Rice,2009,NaN,82.0,{},"{""/m/09c7w0"": ""United States of America""}","{""/m/06cvj"": ""Romantic comedy"", ""/m/02l7c8"": ""..."
23,33427105,/m/0h964n1,Freddy and the Song of the South Pacific,1962-09-12,NaN,97.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama"", ""/m/03k9fj"": ""Adventure""}"
24,31983669,/m/0g4_n3m,Road to Life,1931-09-30,NaN,104.0,"{""/m/06b_j"": ""Russian Language""}","{""/m/05vz3zq"": ""Soviet Union""}","{""/m/07s9rl0"": ""Drama""}"
25,17715326,/m/047t9rb,Camera Thrills,1935-09-01,NaN,25.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02hmvc"": ""Short Film""}"
26,22087420,/m/05pckh0,"Ferdinando I, re di Napoli",1959-12-22,NaN,105.0,"{""/m/02bjrlw"": ""Italian Language""}","{""/m/0f8l9c"": ""France"", ""/m/03rjj"": ""Italy""}","{""/m/01z4y"": ""Comedy"", ""/m/01g6gs"": ""Black-and..."
27,20604092,/m/0523t_1,Anbu Thozhi,2007-08-17,NaN,NaN,"{""/m/07c9s"": ""Tamil Language""}","{""/m/03rk0"": ""India""}","{""/m/02l7c8"": ""Romance Film""}"
28,21344842,/m/05f5_5y,Middle Age Spread,1979,NaN,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0ctw_b"": ""New Zealand""}","{""/m/05p553"": ""Comedy film"", ""/m/07s9rl0"": ""Dr..."
29,156558,/m/014k4y,Baby Boy,2001-06-27,29381649.0,123.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."

In [106]:
a = df_2['Movie genres'].unique()
print(a)

['{"/m/01jfsb": "Thriller", "/m/06n90": "Science Fiction", "/m/03npn": "Horror", "/m/03k9fj": "Adventure", "/m/0fdjb": "Supernatural", "/m/02kdv5l": "Action", "/m/09zvmj": "Space western"}'
 '{"/m/02n4kr": "Mystery", "/m/03bxz7": "Biographical film", "/m/07s9rl0": "Drama", "/m/0hj3n01": "Crime Drama"}'
 '{"/m/0lsxr": "Crime Fiction", "/m/07s9rl0": "Drama"}' ...
 '{"/m/0lsxr": "Crime Fiction", "/m/01jfsb": "Thriller", "/m/01z4y": "Comedy", "/m/0fdjb": "Supernatural"}'
 '{"/m/01z02hx": "Sports", "/m/0lsxr": "Crime Fiction", "/m/02kdv5l": "Action", "/m/07s9rl0": "Drama"}'
 '{"/m/06n90": "Science Fiction", "/m/0gw5n2f": "Japanese Movies", "/m/03k9fj": "Adventure", "/m/0hcr": "Animation", "/m/02hmvc": "Short Film", "/m/0jxy": "Anime", "/m/07s9rl0": "Drama"}']

In [32]:
df_3 = pd.read_csv("name.clusters.txt", sep='\t', header=None)
df_3.head()

               0          1
0  Stuart Little  /m/0k3w9c
1  Stuart Little  /m/0k3wcx
2  Stuart Little  /m/0k3wbn
3       John Doe  /m/0jyg35
4       John Doe  /m/0k2_zn

In [39]:
df_4 = pd.read_csv("plot_summaries.txt", sep='\t', header=None)
df_4.columns = ('Wikipedia movie ID', 'Summary')
df_4.head()

   Wikipedia movie ID                                            Summary
0            23890098  Shlykov, a hard-working taxi driver and Lyosha...
1            31186339  The nation of Panem consists of a wealthy Capi...
2            20663735  Poovalli Induchoodan  is sentenced for six yea...
3             2231378  The Lemon Drop Kid , a New York City swindler,...
4              595909  Seventh-day Adventist Church pastor Michael Ch...

In [60]:
df_5 = pd.read_csv("tvtropes.clusters.txt", sep='\t', header=None)
df_5.columns = ('Character type', 'Instances')
df_5.head()

            Character type                                          Instances
0  absent_minded_professor  {"char": "Professor Philip Brainard", "movie":...
1  absent_minded_professor  {"char": "Professor Keenbean", "movie": "Richi...
2  absent_minded_professor  {"char": "Dr. Reinhardt Lane", "movie": "The S...
3  absent_minded_professor  {"char": "Dr. Harold Medford", "movie": "Them!...
4  absent_minded_professor  {"char": "Daniel Jackson", "movie": "Stargate"...

In [55]:
df_5['Character type'].unique()

array(['absent_minded_professor', 'adventurer_archaeologist',
       'arrogant_kungfu_guy', 'big_man_on_campus', 'bounty_hunter',
       'brainless_beauty', 'broken_bird', 'bromantic_foil',
       'bruiser_with_a_soft_center', 'bully', 'byronic_hero', 'casanova',
       'chanteuse', 'charmer', 'child_prodigy', 'classy_cat_burglar',
       'consummate_professional', 'corrupt_corporate_executive', 'coward',
       'crazy_jealous_guy', 'crazy_survivalist', 'cultured_badass',
       'dean_bitterman', 'dirty_cop', 'ditz', 'doormat',
       'drill_sargeant_nasty', 'dumb_blonde', 'dumb_muscle',
       'eccentric_mentor', 'egomaniac_hunter', 'evil_prince',
       'fastest_gun_in_the_west', 'father_to_his_men', 'final_girl',
       'gadgeteer_genius', 'gentleman_thief', 'granola_person',
       'grumpy_old_man', 'hardboiled_detective', 'heartbroken_badass',
       'henpecked_husband', 'hitman_with_a_heart', 'jerk_jock',
       'junkie_prophet', 'klutz', 'loser_protagonist', 'loveable_rogue',
       'master_swordsman', 'morally_bankrupt_banker',
       'officer_and_a_gentleman', 'ophelia', 'playful_hacker',
       'prima_donna', 'psycho_for_hire', 'pupil_turned_to_evil',
       'retired_outlaw', 'revenge', 'romantic_runnerup', 'self_made_man',
       'slacker', 'stoner', 'storyteller', 'stupid_crooks', 'surfer_dude',
       'the_chief', 'the_editor', 'tranquil_fury', 'trickster',
       'valley_girl', 'warrior_poet', 'young_gun'], dtype=object)

In [58]:
df_5.loc[df_5['Character type'] == 'warrior_poet']

    Character type                                          Instances
486   warrior_poet  {"char": "Katsumoto", "movie": "The Last Samur...
487   warrior_poet  {"char": "Arthur Burns", "movie": "The Proposi...
488   warrior_poet  {"char": "Zohan", "movie": "You Don't Mess wit...
489   warrior_poet  {"char": "Broken Sword", "movie": "Hero", "id"...
490   warrior_poet  {"char": "Colonel Walter E. Kurtz", "movie": "...
491   warrior_poet  {"char": "Master Li Mu Bai", "movie": "Crouchi...
492   warrior_poet  {"char": "Tool", "movie": "The Expendables", "...
493   warrior_poet  {"char": "T. E. Lawrence", "movie": "Lawrence ...
494   warrior_poet  {"char": "Horton the Elephant", "movie": "Hort...

In [59]:
df_5['Instances'][df_5['Character type'] == 'valley_girl']

480    {"char": "Julie Richman", "movie": "Valley Gir...
481    {"char": "Cher Horowitz", "movie": "Clueless",...
482    {"char": "Romy White", "movie": "Romy and Mich...
483    {"char": "Buffy Summers", "movie": "Buffy the ...
484    {"char": "Elle Woods", "movie": "Legally Blond...
485    {"char": "Karen", "movie": "White Chicks", "id...
Name: Instances, dtype: object